### ISSUE TITLE
couldn't get gl visual config

### ISSUE THREAD

**Issue by ghost** [yimyom/odroid-xu4-setup#1]
After 
sudo cp lib/libGL.so.1 /usr/lib/arm-linux-gnueabihf/
sudo ldconfig
and then attempting to run glmark2, I get

LIBGL: ERROR EGL Error detected: EGL_NOT_INITIALIZED
LIBGL: Unable to initialize EGL display.
LIBGL: Unable to initialise EGL.
Error: glxChooseFBConfig() failed
Error: Error: Couldn't get GL visual config!
Error: main: Could not initialize canvas

**Comment by yimyom** [comment]
I'm surprise you get a call to glxChooseFBConfig. Have you tried to run `glmark2` directly on the Linux console or in a terminal in X11? Because `glmark2` is an X11 application and will not work on the console.
There is a version of `glmark2` called `glmark2-es2-fbdev` for the Linux console. Though it doesn't work very well (if not at all) on the XU4 so far.

**Comment by yimyom** [comment]
Solve in the new version
